spring:
  profiles:
    active: dev
  application:
    name: catalog_service

management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics

server:
    port: 9001 
    tomcat:
        connection-timeout: 2s
        keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
atu:
  greeting: Welcome to the local book catalog!
